version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "9090:9000"
    working_dir: /var/www
    restart: always
    volumes:
      - ./:/var/www
      - ~/.composer/composer.json:/home/root/.composer/composer.json
      - ~/.composer/.htaccess:/home/root/.composer/.htaccess
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - database
    networks:
      - app
  nginx:
    image: nginx:${NGINX_VERSION:-stable-alpine}
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - php
    networks:
      - app
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app
volumes:
  database_data:

networks:
  app: